name: build
on: push

jobs:
    build-ubuntu:
        name: build linux
        runs-on: ubuntu-latest
        steps:
        - name: clone repository
          uses: actions/checkout@v2
        - name: configure
          run: |
              mkdir build
              cd build
              cmake ..
        - name: build
          run: cmake --build build
    build-windows:
        name: build windows
        runs-on: windows-latest
        steps:
        - name: clone repository
          uses: actions/checkout@v2
        - name: configure
          run: |
              mkdir build
              cd build
              cmake ..
        - name: build
          run: cmake --build build --config Debug
