name: Run Tests
on: push

jobs:
    build-ubuntu:
        name: Test Linux
        runs-on: ubuntu-latest
        steps:
        - name: clone repository
          uses: actions/checkout@v2
        - name: configure
          run: |
              mkdir build
              cd build
              cmake ..
        - name: build
          run: cmake --build build
        - name: test
          run: |
              cd build
              ./parser
    build-windows:
        name: Test Windows
        runs-on: windows-latest
        steps:
        - name: clone repository
          uses: actions/checkout@v2
        - name: configure
          run: |
              mkdir build
              cd build
              cmake ..
        - name: build
          run: cmake --build build --config Debug
        - name: test
          run: |
              cd build
              cd Debug
              dir
              parser.exe
