name: Run Tests
on: push

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
        - name: clone repository
          uses: actions/checkout@v2
        - name: configure
          run: |
              mkdir build
              cd build
              cmake ..
        - name: build
          run: cmake --build build
        - name: test
          run: |
              cd build
              ls
              ./parser
